/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Formation
 */
public class jp_NewFlight extends javax.swing.JPanel {

    /**
     * Creates new form NewFlightView
     */
    public jp_NewFlight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        JLnewFlight = new javax.swing.JLabel();
        lb_departureCity = new javax.swing.JLabel();
        lb_arrivalCity = new javax.swing.JLabel();
        lb_departureDate = new javax.swing.JLabel();
        lb_departureTime = new javax.swing.JLabel();
        lb_flightDuration = new javax.swing.JLabel();
        lb_flightprice = new javax.swing.JLabel();
        arrivalCity = new javax.swing.JComboBox<>();
        departureDate = new javax.swing.JTextField();
        departureTime = new javax.swing.JTextField();
        flightDuration = new javax.swing.JTextField();
        flightPrice = new javax.swing.JTextField();
        departureCity = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.GridBagLayout());

        JLnewFlight.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        JLnewFlight.setText("Nouveau vol");
        JLnewFlight.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 42, 0);
        add(JLnewFlight, gridBagConstraints);

        lb_departureCity.setText("Ville de départ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(lb_departureCity, gridBagConstraints);

        lb_arrivalCity.setText("Ville d'arrivée");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lb_arrivalCity, gridBagConstraints);

        lb_departureDate.setText("Date de départ (jj/mm/aaaa)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(lb_departureDate, gridBagConstraints);

        lb_departureTime.setText("Heure de départ (hh:mm)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(lb_departureTime, gridBagConstraints);

        lb_flightDuration.setText("Durée du vol (> 9 min)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(lb_flightDuration, gridBagConstraints);

        lb_flightprice.setText("Tarif  en euros au format _,xx");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(lb_flightprice, gridBagConstraints);

        arrivalCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        arrivalCity.setPreferredSize(new java.awt.Dimension(150, 25));
        arrivalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalCityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(arrivalCity, gridBagConstraints);

        departureDate.setText("jTextField2");
        departureDate.setPreferredSize(new java.awt.Dimension(150, 25));
        departureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(departureDate, gridBagConstraints);

        departureTime.setText("jTextField3");
        departureTime.setPreferredSize(new java.awt.Dimension(150, 25));
        departureTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureTimeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(departureTime, gridBagConstraints);

        flightDuration.setText("jTextField4");
        flightDuration.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(flightDuration, gridBagConstraints);

        flightPrice.setText("jTextField5");
        flightPrice.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 7, 0);
        add(flightPrice, gridBagConstraints);

        departureCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        departureCity.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(departureCity, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void arrivalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalCityActionPerformed

    private void departureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureDateActionPerformed

    private void departureTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLnewFlight;
    private javax.swing.JComboBox<String> arrivalCity;
    private javax.swing.JComboBox<String> departureCity;
    private javax.swing.JTextField departureDate;
    private javax.swing.JTextField departureTime;
    private javax.swing.JTextField flightDuration;
    private javax.swing.JTextField flightPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_arrivalCity;
    private javax.swing.JLabel lb_departureCity;
    private javax.swing.JLabel lb_departureDate;
    private javax.swing.JLabel lb_departureTime;
    private javax.swing.JLabel lb_flightDuration;
    private javax.swing.JLabel lb_flightprice;
    // End of variables declaration//GEN-END:variables
}
