/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NewFlightController;

/**
 *
 * @author Formation
 */
public class NewFlightView extends javax.swing.JPanel {

    
    /**
     * Creates new form NewFlightView
     */
    public NewFlightView(NewFlightController nfc) {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        JLnewFlight = new javax.swing.JLabel();
        lb_departureCity = new javax.swing.JLabel();
        lb_arrivalCity = new javax.swing.JLabel();
        lb_departureDate = new javax.swing.JLabel();
        lb_departureTime = new javax.swing.JLabel();
        lb_flightDuration = new javax.swing.JLabel();
        lb_flightprice = new javax.swing.JLabel();
        cb_departureCity = new javax.swing.JComboBox<String>();
        cb_arrivalCity = new javax.swing.JComboBox<String>();
        tf_departureDate = new javax.swing.JTextField();
        tf_departureTime = new javax.swing.JTextField();
        tf_flightDuration = new javax.swing.JTextField();
        tf_flightPrice = new javax.swing.JTextField();
        pb_valid = new javax.swing.JButton();
        pb_cancel = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.GridBagLayout());

        JLnewFlight.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        JLnewFlight.setText("Nouveau vol");
        JLnewFlight.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(21, 21, 21, 21);
        add(JLnewFlight, gridBagConstraints);

        lb_departureCity.setText("Ville de départ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(lb_departureCity, gridBagConstraints);

        lb_arrivalCity.setText("Ville d'arrivée");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 5, 4);
        add(lb_arrivalCity, gridBagConstraints);

        lb_departureDate.setText("Date de départ (jj/mm/aaaa)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(lb_departureDate, gridBagConstraints);

        lb_departureTime.setText("Heure de départ (hh:mm)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(lb_departureTime, gridBagConstraints);

        lb_flightDuration.setText("Durée du vol (> 9 min)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(lb_flightDuration, gridBagConstraints);

        lb_flightprice.setText("Tarif  en euros au format _,xx");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(lb_flightprice, gridBagConstraints);

        cb_departureCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_departureCity.setPreferredSize(new java.awt.Dimension(150, 25));
        cb_departureCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_departureCityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 5, 4);
        add(cb_departureCity, gridBagConstraints);

        cb_arrivalCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_arrivalCity.setPreferredSize(new java.awt.Dimension(150, 25));
        cb_arrivalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_arrivalCityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(cb_arrivalCity, gridBagConstraints);

        tf_departureDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_departureDate.setPreferredSize(new java.awt.Dimension(150, 25));
        tf_departureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_departureDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(tf_departureDate, gridBagConstraints);

        tf_departureTime.setPreferredSize(new java.awt.Dimension(150, 25));
        tf_departureTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_departureTimeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(tf_departureTime, gridBagConstraints);

        tf_flightDuration.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(tf_flightDuration, gridBagConstraints);

        tf_flightPrice.setPreferredSize(new java.awt.Dimension(150, 25));
        tf_flightPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_flightPriceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 12, 4);
        add(tf_flightPrice, gridBagConstraints);

        pb_valid.setText("Valider");
        pb_valid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb_validActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 5, 4);
        add(pb_valid, gridBagConstraints);

        pb_cancel.setText("Annuler");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 4, 5, 4);
        add(pb_cancel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_arrivalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_arrivalCityActionPerformed
        
    }//GEN-LAST:event_cb_arrivalCityActionPerformed

    private void tf_departureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_departureDateActionPerformed
        String departingDate;
    }//GEN-LAST:event_tf_departureDateActionPerformed

    private void tf_departureTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_departureTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_departureTimeActionPerformed

    private void pb_validActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb_validActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pb_validActionPerformed

    private void cb_departureCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_departureCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_departureCityActionPerformed

    private void tf_flightPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_flightPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_flightPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLnewFlight;
    private javax.swing.JComboBox<String> cb_arrivalCity;
    private javax.swing.JComboBox<String> cb_departureCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_arrivalCity;
    private javax.swing.JLabel lb_departureCity;
    private javax.swing.JLabel lb_departureDate;
    private javax.swing.JLabel lb_departureTime;
    private javax.swing.JLabel lb_flightDuration;
    private javax.swing.JLabel lb_flightprice;
    private javax.swing.JButton pb_cancel;
    private javax.swing.JButton pb_valid;
    private javax.swing.JTextField tf_departureDate;
    private javax.swing.JTextField tf_departureTime;
    private javax.swing.JTextField tf_flightDuration;
    private javax.swing.JTextField tf_flightPrice;
    // End of variables declaration//GEN-END:variables
}
